# Generated by Django 3.2.12 on 2024-06-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240604_0525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointmentsss',
            new_name='Booking',
        ),
    ]
